# -*- coding: utf-8 -*-
"""TIC TAC TOE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bND10xT8UnmouSWlS1eUatIxbq_f8pQY
"""

print("Hello World")

def constBoard(Board):
  print("The Current State of Board : \n\n") ;
  for i in range (0,9):
    if (i%3==0 and i>0) :
      print("\n");
    if(Board[i]==0):
      print("_" ,end = ' ');
    if(Board[i]==-1):
      print("X",end = ' ');
    if(Board[i]==1):
      print("O",end = ' ');


def User(Board):
    pos=int(input("ENTER X's POSITION FROM [1,2,3,..9]"))
    if (Board[pos-1]) != 0:
      print("Wrong Move");
      exit(0);
    else:
      Board[pos-1]=-1
      

# 

def minmax(Board,player):
  x=AnalyzeBoard(Board);
  if (x!=0):
    return(x*player);
  pos=-1
  value=-2
  for i in range(0,9):
    if Board[i]==0:
      Board[i]=player;
      score=-minmax(Board,-player);
      Board[i]=0;
      if score>value :
        value=score
        pos=i
  if (pos==-1):
    return 0;
  return value


  # 
  
def CompTurn(Board):
  pos=-1
  value=-2
  for i in range(0,9):
    if Board[i]==0:
      Board[i]=1;
      score=-minmax(Board,-1);
      Board[i]=0;
      if score>value :
        value=score
        pos=i
  Board[pos]=1
  # 
  
def AnalyzeBoard(Board):
     cb=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
     for i in range(0,len(cb)):
       if (Board[cb[i][0]]!=0 and
          Board[cb[i][0]]==Board[cb[i][1]]and
          Board[cb[i][0]]==Board[cb[i][2]]) :
        return Board[cb[i][0]] ;
     return 0
    
   
  # 
def main():
   Board = [0,0,0,0,0,0,0,0,0]
   print("COMPUTER : O VS YOU : X ")


   player=int(input("ENTER TO PLAY FIRST OR SECOND"));
   for i in range(0,9):
    if (AnalyzeBoard(Board)!=0):
      break;
    if (i+player)%2==0:
      CompTurn(Board);
    else:
      constBoard(Board);
      User(Board);
   x=AnalyzeBoard(Board);
   if (x==0):
    constBoard(Board);
    print("DRAW !");
   if (x==-1):
    constBoard(Board);
    print("X Wins")
   if (x==1):
    constBoard(Board);
    print("O Wins")

main()

main()





